### ISSUE TITLE
Feature request: a process that survives shutting down Firefox

### ISSUE THREAD

**Issue by doomkrad** [bobbyrne01/timekeeper-firefox#1]
That says it all, really...

The add-on is a truly big help as-is, however a memory-resident 'chunk' that stays alive after closing Firefox might be an interesting enhancement to consider. Its very existence could be something the user decides upon in the Settings, another setting could be for how long the process should survive: until system shutdown or regardless of system shutdown/restart.

The process could be made visible (for instance) through an icon in the taskbar and the user wouldn't have to keep Firefox open to have access to the time elapsed.

Many thanks!

**Comment by bobbyrne01** [comment]
@doomkrad thanks for stopping by :) unfortunately a process started by an addon cannot outlive the main firefox process, even using [nsIProcess](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIProcess).

perhaps a desktop app/script may better serve your need, which is outside the scope of this addon.
